const express = require('express')
const Post = require('./post')
const profile = require('./profile')
const outbox = require('./outbox')
const inbox = require('./inbox')

module.exports = express.Router()
  .get('/', profile)
  .get('/public_key', profile)
  .get('/outbox', outbox.routers.outbox)
  .get('/inbox', (req, res) => {
    res.status(401).send('Unauthorized')
  })
  .get('/:postId', Post.routers.get)
  .post('/inbox', inbox)
