const express = require('express')
const Post = require('./post')
const profile = require('./profile')
const outbox = require('./outbox')
const inbox = require('./inbox')

module.exports = express.Router()
  .get('/', profile)
  .get('/public_key', profile)
  .get('/outbox/first', outbox.outboxFirst)
  .get('/outbox/last', outbox.outboxLast)
  .get('/outbox', outbox.outbox)
  .get('/inbox', (req, res) => {
    res.status(501).send('Not implemented')
  })
  .get('/:postId', Post.routers.get)
  .post('/inbox', inbox)
  .post('/outbox', (req, res) => {
    res.status(501).send('Not implemented')
  })
